apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  annotations:
    # configmanagement.gke.io/managed: "disabled"
  name: config
  namespace: "gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: ""
        version: "v1"
        kind: "Namespace"
      - group: "extensions"
        version: "v1beta1"
        kind: "Ingress"
