apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
  labels:
    admission.gatekeeper.sh/ignore: no-self-managing
    configmanagement.gke.io/configmanagement: config-management
    control-plane: controller-manager
    gatekeeper.sh/system: "yes"
    k8s-app: kubernetes-config-management
    policycontroller.configmanagement.gke.io: "true"
  ownerReferences:
  - apiVersion: configmanagement.gke.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ConfigManagement
    name: config-management
