apiVersion: v1
kind: Namespace
metadata:
  annotations:
    configmanagement.gke.io/managed: "disabled"
  name: gatekeeper-system
  labels:
    admission.gatekeeper.sh/ignore: no-self-managing
    control-plane: controller-manager
    gatekeeper.sh/system: "yes"
    k8s-app: kubernetes-config-management
    policycontroller.configmanagement.gke.io: "true"
